# Copyright (c) Tile-AI Corporation.
# Licensed under the MIT License.

import glob
import os
import subprocess
import sys

import numpy as np

_DTYPE_MAP = {
    "float16": np.float16,
    "float32": np.float32,
    "float64": np.float64,
    "int8": np.int8,
    "int16": np.int16,
    "int32": np.int32,
    "int64": np.int64,
    "uint8": np.uint8,
    "uint16": np.uint16,
    "uint32": np.uint32,
    "uint64": np.uint64,
    "bool": np.bool_,
}


def read_msaicerr_bin(file_path, dtype=np.float32, shape=None, header_size=0):
    """Read a per-tensor .bin file produced by msaicerr.py.

    Parameters
    ----------
    file_path: str
        Dumped tensor bin file path.
    dtype: np.dtype
        Data type, float32 as default.
    shape: list[int] | tuple[int] | None
        Tensor shape. If None, returns a 1-D array.
    header_size: int
        Bin header size in bytes, 0 as default (pure tensor data).

    Returns
    -------
    np.ndarray
    """
    with open(file_path, "rb") as f:
        if header_size > 0:
            f.read(header_size)
        data = np.frombuffer(f.read(), dtype=dtype)

    if shape is not None:
        data = data.reshape(shape)

    return data.copy()


def _find_msaicerr():
    """Locate CANN's msaicerr.py tool via ASCEND_HOME_PATH."""
    path = os.path.join(
        os.environ.get("ASCEND_HOME_PATH", ""),
        "tools",
        "msaicerr",
        "msaicerr.py",
    )
    return path if os.path.isfile(path) else None


def parse_exception_dump(dump_path, kernel_name="main_kernel", output_dir=None, wait_seconds=2.0):
    """Parse CANN exception dump files generated by acldumpSaveExceptionInfo.

    Finds the latest dump file under
    ``<dump_path>/extra-info/data-dump/<dev>/<kernel_name>.custom.<ts>``,
    parses it with CANN's ``msaicerr.py`` into per-tensor ``.bin`` files, and
    reads them into numpy arrays.

    Call this function inside the ``except`` block after catching an AI Core
    hardware exception (e.g. from ``stream.synchronize()``).

    Parameters
    ----------
    dump_path : str
        The ``ASCEND_DUMP_PATH`` directory where CANN writes dump files.
    kernel_name : str
        The kernel name used as the dump file prefix (passed to
        ``acldumpSaveExceptionInfo`` as ``fileName``).
    output_dir : str, optional
        Directory for parsed ``.bin`` files. Defaults to
        ``<dump_path>/parsed``.
    wait_seconds : float
        Seconds to wait for the dump callback to finish writing before
        searching. The callback runs asynchronously after the exception.

    Returns
    -------
    list[dict]
        Each dict contains:

        - ``'data'``: np.ndarray — the tensor data (1-D; reshape as needed)
        - ``'type'``: str — ``'input'``, ``'output'``, or ``'workspace'``
        - ``'index'``: int — tensor index within its type group
        - ``'dtype'``: str — data type string parsed from filename
        - ``'file'``: str — path to the ``.bin`` file

    Raises
    ------
    FileNotFoundError
        If no dump file is found for *kernel_name*.
    RuntimeError
        If ``msaicerr.py`` is not found or fails to parse.
    """
    import time

    time.sleep(wait_seconds)

    pattern = os.path.join(
        dump_path,
        "extra-info",
        "data-dump",
        "*",
        f"{kernel_name}.custom.*",
    )
    dump_files = sorted(glob.glob(pattern))
    if not dump_files:
        raise FileNotFoundError(f"No exception dump file found for kernel '{kernel_name}' under {os.path.dirname(pattern)}")
    dump_file = dump_files[-1]

    msaicerr_path = _find_msaicerr()
    if msaicerr_path is None:
        raise RuntimeError("msaicerr.py not found. Set ASCEND_HOME_PATH to your CANN install path.")

    if output_dir is None:
        output_dir = os.path.join(dump_path, "parsed")
    os.makedirs(output_dir, exist_ok=True)

    # Remove stale .bin files so only the freshly parsed tensors are returned.
    for stale in glob.glob(os.path.join(output_dir, "*.bin")):
        os.remove(stale)

    ret = subprocess.run(
        [sys.executable, msaicerr_path, "-d", dump_file, "-out", output_dir],
        capture_output=True,
        text=True,
        timeout=60,
    )
    if ret.returncode != 0:
        raise RuntimeError(f"msaicerr.py failed (exit {ret.returncode}):\n{ret.stderr}")

    bin_files = sorted(glob.glob(os.path.join(output_dir, "*.bin")))
    results = []
    for bin_file in bin_files:
        basename = os.path.basename(bin_file)
        parts = basename.split(".")
        # <kernel>.custom.<ts>.<type>.<index>.<dtype>.bin
        dtype_str = parts[-2]
        index = int(parts[-3])
        tensor_type = parts[-4]
        np_dtype = _DTYPE_MAP.get(dtype_str, np.float32)
        data = read_msaicerr_bin(bin_file, dtype=np_dtype)
        results.append(
            {
                "data": data,
                "type": tensor_type,
                "index": index,
                "dtype": dtype_str,
                "file": bin_file,
            }
        )

    return results
